FFA-23_login_design_ui
DIGISO-Digital-Solutions/FamilyFilmApp pull request #12
Opened 2023-07-11 05:10 UTC by rndevelo

UI Login design implement and...
  - Target API 34 (Manifest & Gradle)
  - Extensions.kt
  - Google Fonts Implement
  - Set app logo .svg
  - App icon

2023-07-11 22:49 UTC, Coshiloco commented
Revisa los cambios del deteKT si te vas a los test hay un par de cosas que te dice la herrmaienta esta que implementamos el deteKT que no los pasa

2023-07-11 23:08 UTC, rndevelo commented
> Revisa los cambios del deteKT si te vas a los test hay un par de cosas que te dice la herrmaienta esta que implementamos el deteKT que no los pasa

Tio no se que es lo que pasa

2023-07-13 07:14 UTC, hgarciaalberto requested changes
Here you are have some comments

2023-07-13 07:14 UTC, hgarciaalberto commented on app/build.gradle
> +    compileSdk 34
Usually, these updates are implemented in separated PRs.

2023-07-13 07:14 UTC, hgarciaalberto commented on app/build.gradle
> +        targetSdk 34
same here

2023-07-13 07:14 UTC, hgarciaalberto commented on app/src/main/ic_snail-playstore.png
Can't this images be svg instead?

2023-07-13 07:14 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/Extensions.kt
Do you have any source/documentation on why you decided to implement it this way?

2023-07-13 07:27 UTC, hgarciaalberto commented
@rndevelo I've also seen that the blue color of "Forgot your password" doesn't much very well with the background, don't you think? 
And also the app name in white with the background also in white 🤔. 
Let me know what you guys think.
<img width="360" alt="image" src="https://github.com/DIGISO-Digital-Solutions/FamilyFilmApp/assets/51128924/9f736b3c-70e2-482a-83c5-afb67a661fbb">

2023-07-13 14:35 UTC, rndevelo commented on app/src/main/java/com/digitalsolution/familyfilmapp/Extensions.kt
Yes, this is in "recursitos-calentitos" in our discord

2023-07-13 14:38 UTC, rndevelo commented
> @rndeveloTambién he visto que el color azul de "Olvidaste tu contraseña" no queda muy bien con el fondo, ¿no crees? Y también el nombre de la aplicación en blanco con el fondo también en blanco.🤔. Déjame saber lo que piensas vosotros. <img alt="imagen" width="360" src="https://user-images.githubusercontent.com/51128924/253197273-9f736b3c-70e2-482a-83c5-afb67a661fbb.png">

UI isn't complete, i need that the team aprove FFA22 to color templates or why not define colors templates in FFA23?

2023-07-14 18:31 UTC, rndevelo commented on app/src/main/ic_snail-playstore.png
No, this is a image to mipmap, this isn`t "vector drawable", this is to icon app and launch screen, this should be .png by android studio, and there are the vector drawable in drawable file to use into app too

2023-07-14 18:31 UTC, rndevelo commented on app/src/main/ic_snail-playstore.png
when .svg become android studio will be .xml

2023-07-16 23:55 UTC, hgarciaalberto commented
@rndevelo It seems you have some conflicts with the previous task. It seems you have started your branch before updating you develop branch or develop had just been updated before you have created this branch. Anyway, can you "rebase" your branch and resolve the conflicts? 
Let me know if you have any issue and we can do it together.

2023-07-17 00:47 UTC, hgarciaalberto requested changes
@rndevelo Can you have a look at this comments? I haven't reviewed the composable or the code itself. I'll try to do it sooner than later 🤞

2023-07-17 00:47 UTC, hgarciaalberto commented on app/build.gradle
> +    implementation "androidx.compose.material:material-icons-extended:1.4.3"
Depending on how we finally decide to setup the fonts, this could or couldn't be necessary.

2023-07-17 00:47 UTC, hgarciaalberto commented on app/config/detekt.yml
> +    functionThreshold: 7
Beware of this! Things could go nasty quicker if you start to allow this stuff. 
Sometimes compose force us to add long parameter list but we have to ask ourselves if this is really needed or not and why are we using so many parameters.

2023-07-17 00:47 UTC, hgarciaalberto commented on app/src/main/ic_snail-playstore.png
@rndevelo Going back again to the vectorial image. Are you really sure it is not possible to get this png as a vectorial image so we could get rid of all these files?

2023-07-17 00:47 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/Extensions.kt
Can you double check the links I've shared on discord and share your thoughts about it?
I'm still not fully convinced of this extension function.
https://developer.android.com/jetpack/compose/text/fonts
https://mjmanaog.medium.com/jetpack-compose-tips-how-to-change-font-738917e46f10

cc @Coshiloco

2023-07-17 00:47 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/screens/splash/SplashScreen.kt
> +                painter = painterResource(id = R.drawable.logo_film_family),
Isn't this change part of the `Splash Screen` ticket? I think you shouldn't have this one as part of your PR

2023-07-17 00:47 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/theme/Color.kt
Have you used any web tool to test how the app looks with each color theme?
https://www.materialpalette.com/indigo/amber

2023-07-17 00:47 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/theme/Theme.kt
> +//        }
Why this? I'm not sure if I'm happy with this loss of functionality.

2023-07-17 00:47 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/theme/Type.kt
> +        fontFamily = "Holtwood One SC".getGoogleFontFamily(),
I don't think it is a good practice to use this hardcoded text here.

2023-07-17 00:47 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/theme/Type.kt
> +        fontFamily = "Homenaje".getGoogleFontFamily(),
same here!

2023-07-17 00:47 UTC, hgarciaalberto commented on app/src/main/res/values/ic_snail_background.xml
I don't think this file is needed as this background color can be added in the colors.xml file.

2023-07-17 00:47 UTC, hgarciaalberto commented on app/src/main/res/values/strings.xml
> +    <string name="forgot_your_password">Forgot your password?</string>
I think I need to define a proper way to call elements in the UI. A good practise will be something like: 
`[screen]_[component]_[description]`
 ex: 
  - `login_text_email` 
  - `login_hint_text_email`
  - `login_text_title`
  - ....

2023-07-17 14:27 UTC, rndevelo commented on app/src/main/ic_snail-playstore.png
When you want, I explain you why this is it, look "ic_snail-playstore.png"

2023-07-17 14:32 UTC, rndevelo commented on app/src/main/java/com/digitalsolution/familyfilmapp/Extensions.kt
Title app's typography isn't in android studio's fonts.
Looking for a solution, we can call typography by this library or download font .ttf and install it

2023-07-17 14:33 UTC, rndevelo commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/screens/splash/SplashScreen.kt
> +                painter = painterResource(id = R.drawable.logo_film_family),
You should question for Pablo 🔢

2023-07-17 14:34 UTC, rndevelo commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/theme/Theme.kt
> +//        }
ok, i would like explain you later when we will do call us.

2023-07-17 14:35 UTC, rndevelo commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/theme/Type.kt
> +        fontFamily = "Holtwood One SC".getGoogleFontFamily(),
If you dont want the google library...
I dont see to keep in resources_string if this will be remove.

2023-07-17 14:36 UTC, rndevelo commented on app/src/main/res/values/ic_snail_background.xml
This is created by default when create vector image (drawable)

2023-07-17 14:36 UTC, rndevelo commented on app/src/main/res/values/strings.xml
> +    <string name="forgot_your_password">Forgot your password?</string>
It's ok

2023-07-24 00:07 UTC, Coshiloco approved these changes
Good PUll

2023-07-24 00:27 UTC, merged