FFA-27  connect google button with firebase auth
DIGISO-Digital-Solutions/FamilyFilmApp pull request #32
Opened 2023-08-19 11:14 UTC by Coshiloco

- Add Login with Email and Password
- Add Google Sign In Button

2023-08-22 17:31 UTC, rndevelo requested changes
Look comments Pablo, we need look this

2023-08-22 17:31 UTC, rndevelo commented on app/src/main/java/com/digitalsolution/familyfilmapp/di/GoogleSignInModule.kt
> +
I think that this module should has more things (?)

2023-08-22 17:31 UTC, rndevelo commented on app/src/main/java/com/digitalsolution/familyfilmapp/repositories/LoginRepositoryImpl.kt
> +    override fun loginWithGoogle(idToken: String): Flow<Result<AuthResult>> = callbackFlow {
When I logged with google with app, onSuccess crashed, we should look good this

2023-08-22 17:31 UTC, rndevelo commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/screens/login/LoginScreen.kt
>          LoginContent(
We should create a new branch to create dataclass for parameters

2023-08-22 17:31 UTC, rndevelo commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/screens/login/LoginViewModel.kt
> +    fun googleSignIn(): Intent {
We can call this without return function (?)

2023-09-02 22:22 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/ui/screens/login/LoginViewModel.kt
> +    fun googleSignIn(): Intent {
I've already told him the same and I think it is already fixed

2023-09-09 16:46 UTC, hgarciaalberto approved these changes
Everything's fine

2023-09-09 16:47 UTC, Coshiloco reviewed
Awesome Features

2023-09-09 16:48 UTC, rndevelo approved these changes

2023-09-09 16:50 UTC, rndevelo approved these changes

2023-09-09 16:50 UTC, rndevelo approved these changes

2023-09-09 16:50 UTC, merged