FFA-36 Implement InstallSplashScreen
DIGISO-Digital-Solutions/FamilyFilmApp pull request #42
Opened 2023-09-09 17:48 UTC by rndevelo

2023-09-10 00:03 UTC, hgarciaalberto requested changes
Perfect implementation but just a few improvements... 
Well done crack!

2023-09-10 00:03 UTC, hgarciaalberto commented on app/build.gradle
> +    implementation "androidx.appcompat:appcompat:1.6.1"
This dependency is not required at all: 
`androidx.appcompat:appcompat` 
As you can see yourself, if you remove it, the code compiles just fine.
Can it be removed?

2023-09-10 00:03 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/MainActivity.kt
>          super.onCreate(savedInstanceState)
If there isn't a justified reason to put the `super.onCreate` after the `installSplashScreen().setKeepOnScreenCondition { viewModel.isLoading.value }`
I will suggest switching both lines.

2023-09-10 00:03 UTC, hgarciaalberto commented on app/src/main/java/com/digitalsolution/familyfilmapp/MainViewModel.kt
> +    }
It it does nothing, it is always better to remove unnecessary code

2023-09-11 01:48 UTC, rndevelo commented on app/src/main/java/com/digitalsolution/familyfilmapp/MainActivity.kt
>          super.onCreate(savedInstanceState)
I think that this should be like this, we can test it.

2023-09-12 01:46 UTC, hgarciaalberto approved these changes
Looks fantastic!! 🚀

2023-09-12 01:58 UTC, merged