FFA-7 setup detekt
DIGISO-Digital-Solutions/FamilyFilmApp pull request #9
Opened 2023-06-30 12:16 UTC by Coshiloco

2023-06-30 12:18 UTC, foliolo requested changes
There isn't any config file?

2023-06-30 12:18 UTC, foliolo commented on app/build.gradle
> +    jvmTarget = "1.8"
Can this be changed to java 17?

2023-06-30 12:18 UTC, foliolo commented on app/build.gradle
> +    jvmTarget = "1.8"
This one too

2023-07-02 04:13 UTC, foliolo approved these changes
Looks good after all!

2023-07-02 04:15 UTC, merged

2023-07-02 04:19 UTC, hgarciaalberto reviewed
Looks good